-- Script generated by USE 2.6.2

reset

!create Collab1 : Collaboration
!set Collab1.id := 'Collab1'
!set Collab1.name := 'Collaboration1'
!set Collab1.isClosed := false

!create ConvAssoc1 : ConversationAssociation
!set ConvAssoc1.id := 'ColAssoc1'
!insert (Collab1,ConvAssoc1) into A_conversationAssociations_converstaionAssociations

!create Pool1 : Participant
!set Pool1.id := 'Participant1'
!set Pool1.name := 'Pool1'
!insert (Collab1,Pool1) into A_participants_collaboration

!create Process1 : Process
!set Process1.id := 'Process1'
!set Process1.name := 'Process1'
!set Process1.processType := ProcessType::Public
!set Process1.isExecutable := true
!set Process1.isClosed := false
!insert (Process1,Pool1) into A_processRef_participant

!create LaneSet1 : LaneSet
!set LaneSet1.id := 'LS1'
!set LaneSet1.name := 'LaneSet1'
!insert (Process1,LaneSet1) into A_laneSets_flowElementsContainer

!create Lane1 : Lane
!set Lane1.id := 'L1'
!set Lane1.name := 'Lane1'
!insert (LaneSet1,Lane1) into A_lanes_laneSet

!create Lane2 : Lane
!set Lane2.id := 'L2'
!set Lane2.name := 'Lane2'
!insert (LaneSet1,Lane2) into A_lanes_laneSet

!create Start1 : StartEvent
!set Start1.id := 'EvSt1'
!set Start1.name := 'Start1'
!set Start1.parallelMultiple := false
!set Start1.isInterrupting := false
!insert (Process1,Start1) into A_flowElements_container
!insert (Lane1,Start1) into A_flowNodeRefs_lanes

!create Xor1 : ExclusiveGateway
!set Xor1.id := 'Gw1'
!set Xor1.name := 'Xor1'
!set Xor1.gatewayDirection := GatewayDirection::Diverging
!insert (Process1,Xor1) into A_flowElements_container
!insert (Lane1,Xor1) into A_flowNodeRefs_lanes

!create SeqFlow1 : SequenceFlow
!set SeqFlow1.id := 'SqFlw1'
!set SeqFlow1.name := 'SeqFlow1'
!set SeqFlow1.isImmediate := false
!insert (Process1,SeqFlow1) into A_flowElements_container
!insert (Start1,SeqFlow1) into A_sourceRef_outgoing_flow
!insert (Xor1,SeqFlow1) into A_targetRef_incoming_flow

!create Task1 : Task
!set Task1.id := 'Tsk1'
!set Task1.isForCompensation := false
!set Task1.startQuantity := 1
!set Task1.completionQuantity := 1
!set Task1.name := 'Task1'
!insert (Process1,Task1) into A_flowElements_container
!insert (Lane1,Task1) into A_flowNodeRefs_lanes

!create Task99 : Task
!insert (Process1,Task99) into A_flowElements_container
!insert (Lane1,Task99) into A_flowNodeRefs_lanes


!create SeqFlow2 : SequenceFlow
!set SeqFlow2.id := 'SqFlw2'
!set SeqFlow2.name := 'SeqFlow2'
!set SeqFlow2.isImmediate := false
!insert (Process1,SeqFlow2) into A_flowElements_container
!insert (Xor1,SeqFlow2) into A_sourceRef_outgoing_flow
!insert (SeqFlow2,Xor1) into A_default_exclusiveGateway
!insert (Task1,SeqFlow2) into A_targetRef_incoming_flow
!insert (Task1,SeqFlow2) into A_default_activity

!create Dobj1 : DataObject
!set Dobj1.id := 'Dtobj1'
!set Dobj1.name := 'Dobj1'
!set Dobj1.isCollection := false
!insert (Process1,Dobj1) into A_flowElements_container

!create Association1 : DataInputAssociation
!set Association1.id := 'Association1'
!insert (Dobj1, Association1) into A_sourceRef_dataAssociation
!insert (Task1,Association1) into A_dataInputAssociations_activity

!create DataInput1 : DataInput
!create InputSet1 : InputSet
!insert (DataInput1,Association1) into A_targetRef_dataAssociation
!insert (InputSet1,DataInput1) into A_dataInputRefs_inputSetRefs

!create ItemDefinition1 : ItemDefinition
!set ItemDefinition1.itemKind := ItemKind::Information
!set ItemDefinition1.id := 'ItDef1'
!set ItemDefinition1.isCollection := false
!insert (ItemDefinition1,DataInput1) into A_itemSubjectRef_itemAwareElement
!insert (ItemDefinition1,Dobj1) into A_itemSubjectRef_itemAwareElement

!create IOSpec1 : InputOutputSpecification
!insert (IOSpec1,InputSet1) into A_inputSets_inputOutputSpecification
!insert (IOSpec1,DataInput1) into A_dataInputs_inputOutputSpecification
!insert (Task1,IOSpec1) into A_ioSpecification_activity

!create OutputSet1 : OutputSet
!insert (IOSpec1,OutputSet1) into A_outputSets_inputOutputSpecification

!create Subprocess1 : SubProcess
!insert (Process1,Subprocess1) into A_flowElements_container
!insert (Lane2,Subprocess1) into A_flowNodeRefs_lanes

!create SeqFlow3 : SequenceFlow
!insert (Process1,SeqFlow3) into A_flowElements_container
!insert (Xor1,SeqFlow3) into A_sourceRef_outgoing_flow
!insert (Subprocess1,SeqFlow3) into A_targetRef_incoming_flow

!create Artifact1 : DataStore
!create DataStoreRef1 : DataStoreReference
!insert (Artifact1,DataStoreRef1) into A_dataStoreRef_dataStoreReference
!insert (Process1,DataStoreRef1) into A_flowElements_container

!create Association2 : DataOutputAssociation
!insert (Subprocess1,Association2) into A_dataOutputAssociations_activity
!insert (Artifact1,Association2) into A_targetRef_dataAssociation

!create IOSpec2 : InputOutputSpecification
!insert (Subprocess1,IOSpec2) into A_ioSpecification_activity
!create InputSet2 : InputSet
!create OutputSet2 : OutputSet
!create DataOutput2 : DataOutput
!create ItemDefinition2 : ItemDefinition

!insert (IOSpec2,InputSet2) into A_inputSets_inputOutputSpecification
!insert (IOSpec2,DataOutput2) into A_dataOutputs_inputOutputSpecification
!insert (IOSpec2,OutputSet2) into A_outputSets_inputOutputSpecification
!insert (OutputSet2,DataOutput2) into A_dataOutputRefs_outputSetRefs
!insert (ItemDefinition2,DataOutput2) into A_itemSubjectRef_itemAwareElement
!insert (DataOutput2, Association2) into A_sourceRef_dataAssociation
!insert (ItemDefinition2,Artifact1) into A_itemSubjectRef_itemAwareElement

!create Xor2 : ExclusiveGateway
!set Xor2.id := 'Gw2'
!set Xor2.name := 'Xor2'
!set Xor2.gatewayDirection := GatewayDirection::Converging
!insert (Process1,Xor2) into A_flowElements_container
!insert (Lane2,Xor2) into A_flowNodeRefs_lanes

!create Text1 : TextAnnotation
!set Text1.text := 'Anotação de Xor2'
!set Text1.textFormat := 'text/plain'



!create End1 : EndEvent
!set End1.id := 'EvEnd1'
!set End1.name := 'End1'
!insert (Process1,End1) into A_flowElements_container
!insert (Lane2,End1) into A_flowNodeRefs_lanes

!create SeqFlow4 : SequenceFlow
!set SeqFlow4.id := 'SqFlw4'
!set SeqFlow4.name := 'SeqFlow4'
!set SeqFlow4.isImmediate := false
!insert (Process1,SeqFlow4) into A_flowElements_container
!insert (Task1,SeqFlow4) into A_sourceRef_outgoing_flow
!insert (Xor2,SeqFlow4) into A_targetRef_incoming_flow

!create SeqFlow4a : SequenceFlow
!set SeqFlow4a.id := 'SqFlw4a'
!set SeqFlow4a.name := 'SeqFlow4a'
!set SeqFlow4a.isImmediate := false
!insert (Process1,SeqFlow4a) into A_flowElements_container
!insert (Task1,SeqFlow4a) into A_sourceRef_outgoing_flow
!insert (Subprocess1,SeqFlow4a) into A_targetRef_incoming_flow



!create SeqFlow5 : SequenceFlow
!set SeqFlow5.id := 'SqFlw5'
!set SeqFlow5.name := 'SeqFlow5'
!set SeqFlow5.isImmediate := false
!insert (Process1,SeqFlow5) into A_flowElements_container
!insert (Subprocess1,SeqFlow5) into A_sourceRef_outgoing_flow
!insert (Xor2,SeqFlow5) into A_targetRef_incoming_flow

!create SeqFlow6 : SequenceFlow
!set SeqFlow6.name := 'SeqFlow6'
!set SeqFlow6.id := 'SqFlw6'
!set SeqFlow6.isImmediate := false
!insert (Process1,SeqFlow6) into A_flowElements_container
!insert (Xor2,SeqFlow6) into A_sourceRef_outgoing_flow
!insert (End1,SeqFlow6) into A_targetRef_incoming_flow

!create Association3 : Association
!insert (Xor2,Association3) into A_sourceRef_outgoing_association
!insert (Text1,Association3) into A_targetRef_incoming_association


!create Pool2 : Participant
!set Pool2.id := 'Participant2'
!set Pool2.name := 'Pool2'
!insert (Collab1,Pool2) into A_participants_collaboration
!insert (Process1,Pool2) into A_processRef_participant

!create LaneSet2 : LaneSet
!set LaneSet2.id := 'LS2'
!set LaneSet2.name := 'LaneSet2'
!insert (Process1,LaneSet2) into A_laneSets_flowElementsContainer

!create Lane3 : Lane                            
!set Lane3.id := 'L3'
!set Lane3.name := 'Lane3'
!insert (LaneSet2,Lane3) into A_lanes_laneSet   


!create Start2 : StartEvent
!set Start2.id := 'EvSt2'
!set Start2.name := 'Start2'
!set Start2.parallelMultiple := false
!set Start2.isInterrupting := false
!insert (Process1,Start2) into A_flowElements_container
!insert (Lane3,Start2) into A_flowNodeRefs_lanes

!create Task2 : Task
!set Task2.id := 'Tsk2'
!set Task2.name := 'Task2'
!set Task2.isForCompensation := false
!set Task2.startQuantity := 1
!set Task2.completionQuantity := 1
!insert (Process1,Task2) into A_flowElements_container
!insert (Lane3,Task2) into A_flowNodeRefs_lanes 

!create SeqFlow7 : SequenceFlow
!set SeqFlow7.id := 'SqFlw7'
!set SeqFlow7.name := 'SeqFlow7'
!set SeqFlow7.isImmediate := false
!insert (Process1,SeqFlow7) into A_flowElements_container
!insert (Start2,SeqFlow7) into A_sourceRef_outgoing_flow
!insert (Task2,SeqFlow7) into A_targetRef_incoming_flow

!create End2 : EndEvent
!set End2.id := 'EvEnd2'
!set End2.name := 'End2'
!insert (Process1,End2) into A_flowElements_container
!insert (Lane3,End2) into A_flowNodeRefs_lanes  

!create SeqFlow8 : SequenceFlow
!set SeqFlow8.id := 'SqFlw8'
!set SeqFlow8.name := 'SeqFlow8'
!set SeqFlow8.isImmediate := false
!insert (Process1,SeqFlow8) into A_flowElements_container
!insert (Task2,SeqFlow8) into A_sourceRef_outgoing_flow
!insert (End2,SeqFlow8) into A_targetRef_incoming_flow

!create MesFlow1 : MessageFlow
!insert (End1,MesFlow1) into A_sourceRef_messageFlow
!insert (Start2,MesFlow1) into A_targetRef_messageFlow
!create MesFlow2 : MessageFlow
!insert (Pool1,MesFlow2) into A_sourceRef_messageFlow
!insert (Pool2,MesFlow2) into A_targetRef_messageFlow
!create MesFlow3 : MessageFlow
!insert (Pool1,MesFlow3) into A_sourceRef_messageFlow
!insert (Task2,MesFlow3) into A_targetRef_messageFlow
!create MesFlow4 : MessageFlow
!insert (End2,MesFlow4) into A_sourceRef_messageFlow
!insert (Pool1,MesFlow4) into A_targetRef_messageFlow

!insert (Collab1,MesFlow1) into A_messageFlows_collaboration
!insert (Collab1,MesFlow2) into A_messageFlows_collaboration
!insert (Collab1,MesFlow3) into A_messageFlows_collaboration
!insert (Collab1,MesFlow4) into A_messageFlows_collaboration
!insert (Collab1,Process1) into A_definitionalCollaborationRef_process

!insert (Pool1,Lane1) into A_partitionElementRef_lane
!insert (Pool1,Lane2) into A_partitionElementRef_lane
!insert (Pool2,Lane3) into A_partitionElementRef_lane

check